plugins:
  plugin_manager_update_category_id:
    default: ""
    type: category
    client: true
  plugin_manager_issue_management_site_base_url:
    default: "https://thepavilion.io"
  plugin_manager_issue_management_site_api_token:
    default: ""
  plugin_manager_issue_management_site_api_user:
    default: ""
  plugin_manager_issue_management_site_issue_tags:
    type: list
    default: "automated"
  plugin_manager_issue_management_site_issue_category_id:
    default: ""
    type: integer
    min: 1
  plugin_manager_recommended_coverage_threshold: 70
