plugins:
  plugin_manager_issues_local:
    default: true
  plugin_manager_issues_local_subcategory_name:
    default: issues
    client: true
  plugin_manager_issues_site_base_url:
    default: ""
  plugin_manager_issues_site_api_token:
    default: ""
  plugin_manager_issues_site_api_user:
    default: ""
  plugin_manager_issues_site_issue_tags:
    type: list
    default: "automated"
  plugin_manager_documentation_local_subcategory_name:
    default: documentation
    client: true
  plugin_manager_github_oauth_client_id: ""
  plugin_manager_github_oauth_client_secret: ""
