name: Plugin Tests

on:
  push:
    branches:
      - master
      - main
  pull_request:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build:
    name: ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      DISCOURSE_HOSTNAME: www.example.com
      RUBY_GLOBAL_METHOD_CACHE_SIZE: 131072
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: discourse
      PGPASSWORD: discourse

    strategy:
      fail-fast: false

      matrix:
        build_type: ["backend", "frontend"]
        ruby: ["2.7"]
        postgres: ["12"]
        redis: ["4.x"]

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: discourse
          POSTGRES_PASSWORD: discourse
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          repository: discourse/discourse
          fetch-depth: 1

      - name: Fetch Repo Name
        id: repo-name
        run: echo "::set-output name=value::$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')"

      - name: Install plugin
        uses: actions/checkout@v2
        with:
          path: plugins/${{ steps.repo-name.outputs.value }}
          fetch-depth: 1

      - name: Check spec existence
        id: check_spec
        uses: andstor/file-existence-action@v1
        with:
          files: "plugins/${{ steps.repo-name.outputs.value }}/spec"

      - name: Check qunit existence
        id: check_qunit
        uses: andstor/file-existence-action@v1
        with:
          files: "plugins/${{ steps.repo-name.outputs.value }}/test/javascripts"

      - name: Setup plugin manager server
        run: |
          mkdir -p ${{ github.workspace }}/lib/plugin_guard
          mkdir -p ${{ github.workspace }}/lib/plugin_guard/extensions
          mkdir -p ${{ github.workspace }}/lib/plugin_manager
          mkdir -p ${{ github.workspace }}/lib/plugin_manager/test_host
          mkdir -p ${{ github.workspace }}/lib/plugin_manager/repository_host
          mkdir -p ${{ github.workspace }}/plugins_incompatible
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager_store.rb ${{ github.workspace }}/lib/plugin_manager_store.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard.rb ${{ github.workspace }}/lib/plugin_guard.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard/extensions/discourse.rb ${{ github.workspace }}/lib/plugin_guard/extensions/discourse.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard/extensions/plugin_instance.rb ${{ github.workspace }}/lib/plugin_guard/extensions/plugin_instance.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard/error.rb ${{ github.workspace }}/lib/plugin_guard/error.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard/handler.rb ${{ github.workspace }}/lib/plugin_guard/handler.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_guard/log.rb ${{ github.workspace }}/lib/plugin_guard/log.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager.rb ${{ github.workspace }}/lib/plugin_manager.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/discourse.rb ${{ github.workspace }}/lib/plugin_manager/discourse.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/manifest.rb ${{ github.workspace }}/lib/plugin_manager/manifest.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/notifier.rb ${{ github.workspace }}/lib/plugin_manager/notifier.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/plugin.rb ${{ github.workspace }}/lib/plugin_manager/plugin.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/test_host.rb ${{ github.workspace }}/lib/plugin_manager/test_host.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/test_host/github.rb ${{ github.workspace }}/lib/plugin_manager/test_host/github.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/test_manager.rb ${{ github.workspace }}/lib/plugin_manager/test_manager.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/update.rb ${{ github.workspace }}/lib/plugin_manager/update.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/repository_owner.rb ${{ github.workspace }}/lib/plugin_manager/repository_owner.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/repository_host.rb ${{ github.workspace }}/lib/plugin_manager/repository_host.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/repository_host/github.rb ${{ github.workspace }}/lib/plugin_manager/repository_host/github.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_manager/repository_manager.rb ${{ github.workspace }}/lib/plugin_manager/repository_manager.rb
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/tasks/plugin_guard.rake ${{ github.workspace }}/lib/tasks/plugin_guard.rake
          ln -sf ${{ github.workspace }}/plugins/discourse-plugin-manager-server/lib/plugin_initialization_guard.rb ${{ github.workspace }}/lib/plugin_initialization_guard.rb

      - name: Setup Git
        run: |
          git config --global user.email "ci@ci.invalid"
          git config --global user.name "Discourse CI"

      - name: Setup packages
        run: |
          sudo apt-get update
          sudo apt-get -yqq install postgresql-client libpq-dev gifsicle jpegoptim optipng jhead
          wget -qO- https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-pngquant | sudo sh

      - name: Update imagemagick
        if: matrix.build_type == 'backend'
        run: |
          wget https://raw.githubusercontent.com/discourse/discourse_docker/master/image/base/install-imagemagick
          chmod +x install-imagemagick
          sudo ./install-imagemagick

      - name: Setup redis
        uses: shogo82148/actions-setup-redis@v1
        with:
          redis-version: ${{ matrix.redis }}

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Lint English locale
        if: matrix.build_type == 'backend'
        run: bundle exec ruby script/i18n_lint.rb "plugins/${{ steps.repo-name.outputs.value }}/locales/{client,server}.en.yml"

      - name: Get yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.os }}-yarn-

      - name: Yarn install
        run: yarn install --dev

      - name: Migrate database
        run: |
          bin/rake db:create
          bin/rake db:migrate

      - name: Plugin RSpec with Coverage
        if: matrix.build_type == 'backend' && steps.check_spec.outputs.files_exists == 'true'
        run: SIMPLECOV=1 bin/rake plugin:spec[${{ steps.repo-name.outputs.value }}]

      - name: Plugin QUnit
        if: matrix.build_type == 'frontend' && steps.check_qunit.outputs.files_exists == 'true'
        run: bundle exec rake plugin:qunit['${{ steps.repo-name.outputs.value }}','1200000']
        timeout-minutes: 30
